### ISSUE TITLE
Enhance cache clearing on save to cover more content 

### ISSUE THREAD

**Issue by edwoodward** [openstax/openstax-cms#1324]
### Description
Some items in the CMS are not cleared from the cache when saved. Examples are the Feature Flags and the General Pages. The cache should clear these specifically like it is doing for the pages, footer, sticky note and other content.

### Acceptance Criteria
The cache should be cleared when these items are saved
* General pages
* Feature Flags
* Others will be added

**Comment by nathanstitt** [comment]
I noticed that clearing the cache doesn't seem to be working for the Kinetic homepage. I'm having to use the "Settings->Clear Cloudfront Cache" link in order for my changes to appear.

This happens on both dev, staging, & prod environments.

This may be due to the kinetic page not living under general, instead it's at /kinetic, however I do still see it cached even when accessing it at /general/kinetic

**Comment by brittanyearly** [comment]
Verified in QA for Feature Flag.

**Comment by brittanyearly** [comment]
Verified in Production.
